var text = 'afasadfsadfasfasd';
var text2 = "text2";
console.log(text.length);
var str = 'please locate where is locate';
console.log(str.indexOf('is'));
console.log(str.lastIndexOf('locate'));
console.log(str.search('locate'));
console.log(str.slice(7, 12));
console.log(str.slice(7));
console.log(str.slice(-7));
console.log(str.substring(7, 9));
console.log(str.substr(7, 6));
console.log(str.replace('locate', 'is'));
console.log(str.toUpperCase());
console.log(str.concat(" ", text2));
console.log(str.trim());
console.log(str.charAt(0));
console.log(str.charCodeAt(0));
console.log(str.split(" "));